### ISSUE TITLE
Cant Connect to Open Project Instance

### ISSUE THREAD

**Issue by Jonny12s** [bitswar/VSCodeOpenProject#12]
Hi. I have tried to connect the Openproject self hosted instance v12.12.2 with the Plugin using the API token. I do get a Error massage "Failed connecting to OpenProject" from VSC. 

Any Ideas? Thanks!

**Comment by opilitethesmartdev** [comment]
i've got same issue.
log's saying incorrect credentials.
the token should be simply pasted in, right? no other things?

**Comment by goodhumored** [comment]
> i've got same issue. log's saying incorrect credentials. the token should be simply pasted in, right? no other things?

hi! glad that someone is still using this extension
I'll  try to help
1) Did you set the `base_url` setting?
2) How did you get your token?
3) Tell me exact error message you've got

**Comment by opilitethesmartdev** [comment]
I did set base URL. `opm.opilite.sap.md`. even did paste as plain text. (domain is working but has HTTPS signed by by self-signed CA)

here is the full error i get on VS Code Output:
```
2025-04-03 19:17:53.938 [error] Error: 401 [urn:openproject-org:api:v3:errors:Unauthenticated] You did not provide the correct credentials.
    at EntityManager.fetch (c:\Users\opilite\.vscode\extensions\bitswar.openproject-2.0.0\dist\extension.js:5432:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EntityManager.getMany (c:\Users\opilite\.vscode\extensions\bitswar.openproject-2.0.0\dist\extension.js:5460:33)
```

I got token from `GUI > Administration > System Settings > Repositories > API Key`
the api key env variable in `/etc/openproject/conf.d/other`  is the same aswell

**Comment by goodhumored** [comment]
> I did set base URL. `opm.opilite.sap.md`. even did paste as plain text. (domain is working but has HTTPS signed by by self-signed CA)
> 
> here is the full error i get on VS Code Output:
> ```
> 2025-04-03 19:17:53.938 [error] Error: 401 [urn:openproject-org:api:v3:errors:Unauthenticated] You did not provide the correct credentials.
>     at EntityManager.fetch (c:\Users\opilite\.vscode\extensions\bitswar.openproject-2.0.0\dist\extension.js:5432:31)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at EntityManager.getMany (c:\Users\opilite\.vscode\extensions\bitswar.openproject-2.0.0\dist\extension.js:5460:33)
> ```
> 
> I got token from `GUI > Administration > System Settings > Repositories > API Key`
> the api key env variable in `/etc/openproject/conf.d/other`  is the same aswell
> 

Not sure, but I guess you got the wrong token

You need to get a **personal access token** from your account settings

**Comment by opilitethesmartdev** [comment]
Ohh, i see.

Still not working.
Just generated an API Key, still the same error

**Comment by opilitethesmartdev** [comment]
suddenly it worked. maybe a reboot did it?
